### ISSUE TITLE
Can't Buy-It-Now after you've bid

### ISSUE THREAD

**Issue by King-i8** [ZombieStriker/NPCAuctions#11]
Once you've bid on an item, and afterward decide to Buy-It-Now, you're prevented from doing so, as the game will tell you that you've already bid on that item.

**Comment by Aero4K** [comment]
Once you've bid on a certain item, and afterward decide to Buy-It-Now, you're prevented from doing so, as the game will tell you that you've already bid on that item.

**Comment by ZombieStriker** [comment]
This has been addressed in the new update. You can now use the buy it now option for auctions you have bid on.
