### ISSUE TITLE
Different inventory problem

### ISSUE THREAD

**Issue by Jeremylo1** [ZombieStriker/NPCAuctions#5]
There is a big problem with your plugin for some types of server. For example, if a player is in an arena in another world with a different inventory like the mobarena and his item is not selling, are item going to come into his arena inventory and when he get out of the arena he will lose his item. The item should be stored and the player can pick it up directly with the NPC.

Your plugin is one of a kind, simple and practical, but I can not use it for the moment. Can you add this function please?
**(Sorry, I'm french)**

**Comment by ZombieStriker** [comment]
This issue was fixed in v1.0.52
